"""Generate Pico's original grayscale app icons and the existing small setting symbols."""
from __future__ import annotations

import importlib.util
import math
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
PREVIEW = ROOT / "previews/ux-v09/render.py"
OUTPUT = ROOT / "main/assets/app_icons.h"
SHEET = ROOT / "previews/ux-v06/app-icons-v2.png"
SCALE = 4


def app_icon(name: str, preview=None) -> Image.Image:
    if preview is not None and name != "weread":
        image = Image.new("RGB", (80, 80), "white")
        preview.app_icon(image, 40, 40, name)
        return image.convert("L")
    image = Image.new("L", (80 * SCALE, 80 * SCALE), 255)
    draw = ImageDraw.Draw(image)
    p = lambda n: round(n * SCALE)
    box = lambda coords: tuple(p(v) for v in coords)
    line = lambda pts, fill=55, width=2.4: draw.line([(p(x), p(y)) for x, y in pts], fill=fill, width=p(width), joint="curve")
    round_rect = lambda coords, radius, fill, outline=55, width=2: draw.rounded_rectangle(
        box(coords), radius=p(radius), fill=fill, outline=outline, width=p(width))
    if name == "picture":
        round_rect((20, 12, 66, 57), 3, 220, 112, 2)
        round_rect((14, 19, 60, 65), 3, 246, 45, 2.5)
        draw.ellipse(box((43, 29, 51, 37)), fill=92)
        line([(18, 55), (30, 42), (38, 48), (45, 39), (57, 52)], 62, 2.5)
        line([(20, 60), (53, 60)], 170, 1.4)
    elif name == "transfer":
        round_rect((29, 11, 51, 31), 3, 224, 62, 2)
        draw.rectangle(box((34, 15, 37, 20)), fill=83)
        draw.rectangle(box((43, 15, 46, 20)), fill=83)
        round_rect((22, 27, 58, 68), 7, 225, 52, 2.5)
        line([(23, 37), (57, 37)], 128, 1.8)
        draw.ellipse(box((35, 48, 45, 58)), fill=255, outline=82, width=p(2))
        line([(28, 63), (52, 63)], 153, 1.4)
    elif name == "manage":
        round_rect((13, 22, 28, 64), 2, 231, 61, 2)
        round_rect((30, 15, 45, 64), 2, 174, 57, 2)
        round_rect((47, 25, 63, 64), 2, 214, 61, 2)
        for x, y in ((17, 31), (34, 24), (51, 34)):
            line([(x, y), (x + 7, y)], 100, 1.5)
            line([(x, y + 4), (x + 7, y + 4)], 150, 1)
        line([(9, 66), (67, 66)], 43, 2.5)
    elif name == "settings":
        draw.ellipse(box((12, 12, 68, 68)), fill=236, outline=55, width=p(2.5))
        draw.ellipse(box((21, 21, 59, 59)), fill=186, outline=78, width=p(1.7))
        draw.ellipse(box((30, 30, 50, 50)), fill=247, outline=52, width=p(2.3))
        draw.ellipse(box((36, 36, 44, 44)), fill=81)
        for angle in (0, 45, 90, 135, 180, 225, 270, 315):
            a = math.radians(angle)
            r0, r1 = (27, 33) if angle % 90 == 0 else (29, 32)
            line([(40 + math.cos(a) * r0, 40 + math.sin(a) * r0),
                  (40 + math.cos(a) * r1, 40 + math.sin(a) * r1)], 72, 2)
    elif name == "weread":
        draw.rounded_rectangle(box((11, 13, 69, 67)), radius=p(12), fill=106)
        draw.polygon([tuple(map(p, point)) for point in
                      ((18, 23), (32, 20), (40, 27), (48, 20), (62, 23),
                       (62, 55), (48, 53), (40, 59), (32, 53), (18, 55))], fill=255)
        line([(40, 28), (40, 57)], 106, 2)
        line([(23, 30), (32, 29)], 157, 1.5)
        line([(48, 29), (57, 30)], 157, 1.5)
    else:
        raise ValueError(name)
    return image.resize((80, 80), Image.Resampling.LANCZOS)


def packed_4bpp(image: Image.Image) -> list[int]:
    gray = [max(0, min(15, round(v / 17))) for v in image.convert("L").getdata()]
    return [(gray[i] << 4) | gray[i + 1] for i in range(0, len(gray), 2)]


def append_icon(lines: list[str], image: Image.Image) -> None:
    values = packed_4bpp(image)
    lines.append("    {")
    for start in range(0, len(values), 20):
        lines.append("        " + ", ".join(f"0x{byte:02x}" for byte in values[start:start + 20]) + ",")
    lines.append("    },")


def main() -> None:
    spec = importlib.util.spec_from_file_location("pico_preview", PREVIEW)
    preview = importlib.util.module_from_spec(spec)
    assert spec.loader
    spec.loader.exec_module(preview)
    names = ("picture", "transfer", "manage", "settings", "weread")
    icons = [app_icon(name, preview) for name in names]
    sheet = Image.new("L", (5 * 160, 160), 238)
    for i, icon in enumerate(icons):
        sheet.paste(icon.resize((120, 120), Image.Resampling.NEAREST), (i * 160 + 20, 20))
    sheet.save(SHEET)
    lines = [
        "/*",
        " * 中文：由 tools/gen_app_icons.py 生成；应用图标为 Pico 原创灰阶绘图，勿手改。",
        " * English: Generated by tools/gen_app_icons.py; app icons are original Pico grayscale artwork.",
        " */",
        "#pragma once", "#include <stdint.h>",
        "#define PICO_APP_ICON_SIZE 80",
        "static const uint8_t pico_app_icons[5][PICO_APP_ICON_SIZE * PICO_APP_ICON_SIZE / 2] = {",
    ]
    for icon in icons:
        append_icon(lines, icon)
    lines.append("};")
    lines.append("#define PICO_SETTING_ICON_SIZE 32")
    lines.append("static const uint8_t pico_setting_icons[7][PICO_SETTING_ICON_SIZE * PICO_SETTING_ICON_SIZE / 2] = {")
    for name in ("wifi", "bluetooth", "font", "spacing", "shelf", "ticket", "clock"):
        image = Image.new("RGB", (32, 32), "white")
        preview.setting_icon(image, 16, 16, name)
        append_icon(lines, image)
    lines.append("};")
    OUTPUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
